version: "3.8"

services:
  fluxgym:
    build:
      context: .
      # Change the dockerfile to Dockerfile.cuda12.4 if running CUDA 12.4 drivers
      dockerfile: Dockerfile
    image: fluxgym
    container_name: fluxgym
    network_mode: "host"  # <-- Enables host networking
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./:/app/fluxgym
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    restart: unless-stopped
